### ISSUE TITLE
没有源码？

### ISSUE THREAD

**Issue by songhaoying** [SMILEORIGIN/TC#1]

**Comment by smileorigin** [comment]
本人现在是新手，代码水平也一般，并不是不想开源，实在是愧于代码一般，如果有一部分人真的需要我会开源的，这也是对你们支持的感谢,如果真的需要麻烦你们issues,start或者watch，事后可以在取消，如果总的够20，我会把源码上传，感谢理解，抱歉

**Comment by jp1017** [comment]
开源促进发展，啦啦啦

**Comment by smileorigin** [comment]
源码已上传，感谢支持，十分感谢
