### ISSUE TITLE
另外建议作者在主界面上增加一个小动画，用来表示上传剪贴板截图的过程。

### ISSUE THREAD

**Issue by songhaoying** [SMILEORIGIN/TC#3]
建议作者在主界面上增加一个小动画，用来表示上传剪贴板截图的过程。
这样的话一目了然就可以知道软件有没有在上传图片。体验会更好。

另外建议实现  ctrl+c    ctrl+v的形式完成上转。

譬如我截完图之后，直接在工具的主界面按ctrl+v就能完成上传。 或者是复制本地图片之后，在主界面上按ctrl+v 就能上传。 这样操作起来更方便，更人性化。

再次感谢作者，提供了这么好用的工具。

**Comment by smileorigin** [comment]
感谢支持，因为这几个月电脑坏了，没有电脑可以做开发，知道现在才看到你的issues，很抱歉。我也想加个动画，慢慢学习了，已经大半年没写代码了，后面有空一起完善，上传动画这个很不错的建议，后面我会考虑加上去，一开始是为了整体的简洁性，想要在写作的时候进行无缝的图片上传，感觉不到工具的存在，所以就没弄了，可以直接拉图片到窗口就可以上传啦，快捷键的话可以考虑加下 这个靠谱，我比较喜欢用的是配合QQ截图，开启截图监听，这样写笔记就速度很快
